#pragma once

#include "source2sdk/source2gen/source2gen.hpp"
#include <cstddef>
#include <cstdint>

// /////////////////////////////////////////////////////////////
// Module: client
// Created using source2gen - github.com/neverlosecc/source2gen
// /////////////////////////////////////////////////////////////

namespace source2sdk
{
    namespace client
    {
        // Enumerator count: 147
        // Alignment: 4
        // Size: 0x4
        enum class EGCItemMsg : std::uint32_t
        {
            k_EMsgGCBase = 0x3e8,
            k_EMsgGCSetItemPosition = 0x3e9,
            k_EMsgGCCraft = 0x3ea,
            k_EMsgGCCraftResponse = 0x3eb,
            k_EMsgGCDelete = 0x3ec,
            k_EMsgGCVerifyCacheSubscription = 0x3ed,
            k_EMsgGCNameItem = 0x3ee,
            k_EMsgGCUnlockCrate_DEPRECATED = 0x3ef,
            k_EMsgGCUnlockCrateResponse = 0x3f0,
            k_EMsgGCPaintItem = 0x3f1,
            k_EMsgGCPaintItemResponse = 0x3f2,
            k_EMsgGCGoldenWrenchBroadcast = 0x3f3,
            k_EMsgGCMOTDRequest = 0x3f4,
            k_EMsgGCMOTDRequestResponse = 0x3f5,
            k_EMsgGCAddItemToSocket_DEPRECATED = 0x3f6,
            k_EMsgGCAddItemToSocketResponse_DEPRECATED = 0x3f7,
            k_EMsgGCAddSocketToBaseItem_DEPRECATED = 0x3f8,
            k_EMsgGCAddSocketToItem_DEPRECATED = 0x3f9,
            k_EMsgGCAddSocketToItemResponse_DEPRECATED = 0x3fa,
            k_EMsgGCNameBaseItem = 0x3fb,
            k_EMsgGCNameBaseItemResponse = 0x3fc,
            k_EMsgGCRemoveSocketItem_DEPRECATED = 0x3fd,
            k_EMsgGCRemoveSocketItemResponse_DEPRECATED = 0x3fe,
            k_EMsgGCCustomizeItemTexture = 0x3ff,
            k_EMsgGCCustomizeItemTextureResponse = 0x400,
            k_EMsgGCUseItemRequest = 0x401,
            k_EMsgGCUseItemResponse = 0x402,
            k_EMsgGCGiftedItems_DEPRECATED = 0x403,
            k_EMsgGCRemoveItemName = 0x406,
            k_EMsgGCRemoveItemPaint = 0x407,
            k_EMsgGCGiftWrapItem = 0x408,
            k_EMsgGCGiftWrapItemResponse = 0x409,
            k_EMsgGCDeliverGift = 0x40a,
            k_EMsgGCDeliverGiftResponseGiver = 0x40b,
            k_EMsgGCDeliverGiftResponseReceiver = 0x40c,
            k_EMsgGCUnwrapGiftRequest = 0x40d,
            k_EMsgGCUnwrapGiftResponse = 0x40e,
            k_EMsgGCSetItemStyle = 0x40f,
            k_EMsgGCUsedClaimCodeItem = 0x410,
            k_EMsgGCSortItems = 0x411,
            k_EMsgGC_RevolvingLootList_DEPRECATED = 0x412,
            k_EMsgGCLookupAccount = 0x413,
            k_EMsgGCLookupAccountResponse = 0x414,
            k_EMsgGCLookupAccountName = 0x415,
            k_EMsgGCLookupAccountNameResponse = 0x416,
            k_EMsgGCUpdateItemSchema = 0x419,
            k_EMsgGCRemoveCustomTexture = 0x41b,
            k_EMsgGCRemoveCustomTextureResponse = 0x41c,
            k_EMsgGCRemoveMakersMark = 0x41d,
            k_EMsgGCRemoveMakersMarkResponse = 0x41e,
            k_EMsgGCRemoveUniqueCraftIndex = 0x41f,
            k_EMsgGCRemoveUniqueCraftIndexResponse = 0x420,
            k_EMsgGCSaxxyBroadcast = 0x421,
            k_EMsgGCBackpackSortFinished = 0x422,
            k_EMsgGCCollectItem = 0x425,
            k_EMsgGCItemAcknowledged__DEPRECATED = 0x426,
            k_EMsgGC_ReportAbuse = 0x429,
            k_EMsgGC_ReportAbuseResponse = 0x42a,
            k_EMsgGCNameItemNotification = 0x42c,
            k_EMsgGCApplyConsumableEffects = 0x42d,
            k_EMsgGCConsumableExhausted = 0x42e,
            k_EMsgGCShowItemsPickedUp = 0x42f,
            k_EMsgGCClientDisplayNotification = 0x430,
            k_EMsgGCApplyStrangePart = 0x431,
            k_EMsgGC_IncrementKillCountAttribute = 0x432,
            k_EMsgGC_IncrementKillCountResponse = 0x433,
            k_EMsgGCApplyPennantUpgrade = 0x434,
            k_EMsgGCSetItemPositions = 0x435,
            k_EMsgGCApplyEggEssence = 0x436,
            k_EMsgGCNameEggEssenceResponse = 0x437,
            k_EMsgGCPaintKitItem = 0x438,
            k_EMsgGCPaintKitBaseItem = 0x439,
            k_EMsgGCPaintKitItemResponse = 0x43a,
            k_EMsgGCGiftedItems = 0x43b,
            k_EMsgGCUnlockItemStyle = 0x43c,
            k_EMsgGCUnlockItemStyleResponse = 0x43d,
            k_EMsgGCApplySticker = 0x43e,
            k_EMsgGCItemAcknowledged = 0x43f,
            k_EMsgGCStatTrakSwap = 0x440,
            k_EMsgGCUserTrackTimePlayedConsecutively = 0x441,
            k_EMsgGCItemCustomizationNotification = 0x442,
            k_EMsgGCModifyItemAttribute = 0x443,
            k_EMsgGCCasketItemAdd = 0x444,
            k_EMsgGCCasketItemExtract = 0x445,
            k_EMsgGCCasketItemLoadContents = 0x446,
            k_EMsgGCTradingBase = 0x5dc,
            k_EMsgGCTrading_InitiateTradeRequest = 0x5dd,
            k_EMsgGCTrading_InitiateTradeResponse = 0x5de,
            k_EMsgGCTrading_StartSession = 0x5df,
            k_EMsgGCTrading_SetItem = 0x5e0,
            k_EMsgGCTrading_RemoveItem = 0x5e1,
            k_EMsgGCTrading_UpdateTradeInfo = 0x5e2,
            k_EMsgGCTrading_SetReadiness = 0x5e3,
            k_EMsgGCTrading_ReadinessResponse = 0x5e4,
            k_EMsgGCTrading_SessionClosed = 0x5e5,
            k_EMsgGCTrading_CancelSession = 0x5e6,
            k_EMsgGCTrading_TradeChatMsg = 0x5e7,
            k_EMsgGCTrading_ConfirmOffer = 0x5e8,
            k_EMsgGCTrading_TradeTypingChatMsg = 0x5e9,
            k_EMsgGCServerBrowser_FavoriteServer = 0x641,
            k_EMsgGCServerBrowser_BlacklistServer = 0x642,
            k_EMsgGCServerRentalsBase = 0x6a4,
            k_EMsgGCItemPreviewCheckStatus = 0x6a5,
            k_EMsgGCItemPreviewStatusResponse = 0x6a6,
            k_EMsgGCItemPreviewRequest = 0x6a7,
            k_EMsgGCItemPreviewRequestResponse = 0x6a8,
            k_EMsgGCItemPreviewExpire = 0x6a9,
            k_EMsgGCItemPreviewExpireNotification = 0x6aa,
            k_EMsgGCItemPreviewItemBoughtNotification = 0x6ab,
            k_EMsgGCDev_NewItemRequest = 0x7d1,
            k_EMsgGCDev_NewItemRequestResponse = 0x7d2,
            k_EMsgGCDev_PaintKitDropItem = 0x7d3,
            k_EMsgGCDev_SchemaReservationRequest = 0x7d4,
            k_EMsgGCStoreGetUserData = 0x9c4,
            k_EMsgGCStoreGetUserDataResponse = 0x9c5,
            k_EMsgGCStorePurchaseInit_DEPRECATED = 0x9c6,
            k_EMsgGCStorePurchaseInitResponse_DEPRECATED = 0x9c7,
            k_EMsgGCStorePurchaseFinalize = 0x9c8,
            k_EMsgGCStorePurchaseFinalizeResponse = 0x9c9,
            k_EMsgGCStorePurchaseCancel = 0x9ca,
            k_EMsgGCStorePurchaseCancelResponse = 0x9cb,
            k_EMsgGCStorePurchaseQueryTxn = 0x9cc,
            k_EMsgGCStorePurchaseQueryTxnResponse = 0x9cd,
            k_EMsgGCStorePurchaseInit = 0x9ce,
            k_EMsgGCStorePurchaseInitResponse = 0x9cf,
            k_EMsgGCBannedWordListRequest = 0x9d0,
            k_EMsgGCBannedWordListResponse = 0x9d1,
            k_EMsgGCToGCBannedWordListBroadcast = 0x9d2,
            k_EMsgGCToGCBannedWordListUpdated = 0x9d3,
            k_EMsgGCToGCDirtySDOCache = 0x9d4,
            k_EMsgGCToGCDirtyMultipleSDOCache = 0x9d5,
            k_EMsgGCToGCUpdateSQLKeyValue = 0x9d6,
            k_EMsgGCToGCIsTrustedServer = 0x9d7,
            k_EMsgGCToGCIsTrustedServerResponse = 0x9d8,
            k_EMsgGCToGCBroadcastConsoleCommand = 0x9d9,
            k_EMsgGCServerVersionUpdated = 0x9da,
            k_EMsgGCToGCWebAPIAccountChanged = 0x9dc,
            k_EMsgGCRequestAnnouncements = 0x9dd,
            k_EMsgGCRequestAnnouncementsResponse = 0x9de,
            k_EMsgGCRequestPassportItemGrant = 0x9df,
            k_EMsgGCClientVersionUpdated = 0x9e0,
            k_EMsgGCRecurringSubscriptionStatus = 0x9e2,
            k_EMsgGCAdjustEquipSlotsManual = 0x9e3,
            k_EMsgGCAdjustEquipSlotsShuffle = 0x9e4,
            k_EMsgGCOpenCrate = 0x9e6,
            k_EMsgGCAcknowledgeRentalExpiration = 0x9e7,
            k_EMsgGCVolatileItemLoadContents = 0x9e8,
        };
    };
};
