// Autogenerated! Do not edit.
#pragma once

// size derived from field layout; consistent across 3 usages
typedef char BASEPTR[0x08];
// size derived from field layout
typedef char CAnimGraph2ParamAutoResetOptionalRef[0x20];
// skipped template CAnimGraphParamOptionalRef
// skipped template CAnimGraphParamRef
typedef char CAnimGraphTagOptionalRef[0x18];
typedef char CAnimGraphTagRef[0x18];
// skipped template CAnimScriptParam
// skipped template CAnimValue
typedef char CAnimVariant[0x11];
typedef char CAttachmentNameSymbolWithStorage[0x20];
// skipped template CBitVec
typedef char CBufferString[0x10];
typedef char CColorGradient[0x18];
// skipped template CCompressor
typedef char CEntityHandle[0x04];
typedef char CEntityIndex[0x04];
// size derived from field layout
typedef char CEntityNameString[0x08];
// skipped template CEntityOutputTemplate
// size derived from field layout; consistent across 43 usages
typedef char CGameSoundEventName[0x08];
typedef char CGlobalSymbol[0x08];
typedef char CGlobalSymbolCaseSensitive[0x08];
// skipped template CHandle
typedef char CKV3MemberNameSet[0x10];
typedef char CKV3MemberNameWithStorage[0x38];
// size derived from field layout
typedef char CModelAnimNameWithDeltas[0x08];
// size derived from field layout
typedef char CModelMaterialGroupName[0x08];
// size derived from field layout
typedef char CMotionTransform[0x10];
// skipped template CNetworkUtlVectorBase
typedef char CNetworkedQuantizedFloat[0x08];
typedef char CPanoramaImageName[0x10];
typedef char CParticleNamedValueRef[0x40];
typedef char CPiecewiseCurve[0x40];
typedef char CPlayerSlot[0x04];
// was 0x10; current CS2 matches the larger Deadlock layout — all 10 usages in the dump agree on 0x18
typedef char CPulseValueFullType[0x18];
// skipped template CResourceArray
typedef char CResourceName[0xe0];
// skipped template CResourceNameTyped
// skipped template CResourcePointer
// size unknown
typedef char CResourceString[0x08];
// size derived from field layout; consistent across 2 usages
typedef char CRotation[0x04];
typedef char CSmartPropAttributeAngles[0x40];
typedef char CSmartPropAttributeBool[0x40];
typedef char CSmartPropAttributeColor[0x40];
typedef char CSmartPropAttributeFloat[0x40];
typedef char CSmartPropAttributeInt[0x40];
typedef char CSmartPropAttributeMaterialGroup[0x40];
typedef char CSmartPropAttributeMaterialName[0x40];
typedef char CSmartPropAttributeModelName[0x40];
typedef char CSmartPropAttributeStateName[0x40];
// size derived from field layout; matches every other CSmartPropAttribute*
typedef char CSmartPropAttributeSurfaceProperty[0x40];
typedef char CSmartPropAttributeVariableValue[0x40];
typedef char CSmartPropAttributeVector[0x40];
typedef char CSmartPropAttributeVector2D[0x40];
typedef char CSmartPropVariableComparison[0x20];
// skipped template CSmartPtr
typedef char CSoundEventName[0x10];
typedef char CSplitScreenSlot[0x04];
// skipped template CStrongHandle
// skipped template CStrongHandleCopyable
// size doesn't matter. only used as a pointer
typedef char CStrongHandleVoid[0x08];
typedef char CTransform[0x20];
// size derived from field layout; consistent across 7 usages
typedef char CTransformWS[0x20];
// shrank from 0x18 in current CS2; all 16 usages in the dump agree on 0x10
typedef char CUtlBinaryBlock[0x10];
// skipped template CUtlHashtable
// skipped template CUtlLeanVector
// skipped template CUtlLeanVectorFixedGrowable
// skipped template CUtlOrderedMap
// skipped template CUtlPair
typedef char CUtlString[0x08];
typedef char CUtlStringToken[0x04];
typedef char CUtlStringTokenWithStorage[0x18];
typedef char CUtlSymbol[0x02];
typedef char CUtlSymbolLarge[0x08];
// skipped template CUtlVector
// skipped template CUtlVectorEmbeddedNetworkVar
// skipped template CUtlVectorFixedGrowable
typedef char CUtlVectorSIMDPaddedVector[0x18];
// skipped template CVariantBase
// skipped template CWeakHandle
// skipped template C_NetworkUtlVectorBase
// skipped template C_UtlVectorEmbeddedNetworkVar
typedef char Color[0x04];
typedef char DegreeEuler[0x0c];
// size derived from field layout; consistent across 2 usages
typedef char ENTITYFUNCPTR[0x08];
typedef char FourVectors[0x30];
// size derived from field layout
typedef char HPulseCellBase[0x08];
typedef char HSCRIPT[0x08];
// size derived from field layout
typedef char HYieldedCursor[0x0c];
// size doesn't matter. only used as a pointer
typedef char KeyValues[0x01];
typedef char KeyValues3[0x10];
// size derived from field layout
typedef char ParticleParamID_t[0x10];
typedef char PulseSymbol_t[0x10];
typedef char QAngle[0x0c];
typedef char Quaternion[0x10];
typedef char QuaternionStorage[0x10];
typedef char RadianEuler[0x0c];
typedef char Range_t[0x08];
// size derived from field layout; matches Vector centre + float radius
typedef char RnSphere_t[0x10];
typedef char RotationVector[0x0c];
// skipped template SphereBase_t
// size derived from field layout
typedef char USEPTR[0x08];
typedef char V_uuid_t[0x10];
typedef char Vector[0x0c];
typedef char Vector2D[0x08];
typedef char Vector4D[0x10];
typedef char VectorAligned[0x10];
typedef char VectorWS[0x0c];
typedef char WorldGroupId_t[0x04];
typedef char float32[0x04];
typedef char fltx4[0x10];
typedef char matrix3x4_t[0x30];
typedef char matrix3x4a_t[0x30];
typedef char panorama_CPanelPtr[0x08];
