#pragma once

#include "source2sdk/source2gen/source2gen.hpp"
#include <cstddef>
#include <cstdint>

// /////////////////////////////////////////////////////////////
// Module: client
// Created using source2gen - github.com/neverlosecc/source2gen
// /////////////////////////////////////////////////////////////

namespace source2sdk
{
    namespace client
    {
        // Enumerator count: 409
        // Alignment: 4
        // Size: 0x4
        enum class modifierfunction : std::uint32_t
        {
            // MScriptDescription "GetModifierPreAttack_BonusDamage"
            MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE = 0x0,
            // MScriptDescription "GetModifierPreAttack_BonusDamage_Target"
            MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE_TARGET = 0x1,
            // MScriptDescription "GetModifierPreAttack_BonusDamage_Proc"
            MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE_PROC = 0x2,
            // MScriptDescription "GetModifierPreAttack_BonusDamagePostCrit"
            MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE_POST_CRIT = 0x3,
            // MScriptDescription "GetModifierBaseAttack_BonusDamage"
            MODIFIER_PROPERTY_BASEATTACK_BONUSDAMAGE = 0x4,
            // MScriptDescription "GetModifierProcAttack_BonusDamage_Physical"
            MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PHYSICAL = 0x5,
            // MScriptDescription "GetModifierProcAttack_ConvertPhysicalToMagical"
            MODIFIER_PROPERTY_PROCATTACK_CONVERT_PHYSICAL_TO_MAGICAL = 0x6,
            // MScriptDescription "GetModifierProcAttack_BonusDamage_Magical"
            MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_MAGICAL = 0x7,
            // MScriptDescription "GetModifierProcAttack_BonusDamage_Pure"
            MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PURE = 0x8,
            // MScriptDescription "GetModifierProcAttack_BonusDamage_Magical_Target"
            MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_MAGICAL_TARGET = 0x9,
            // MScriptDescription "GetModifierProcAttack_Feedback"
            MODIFIER_PROPERTY_PROCATTACK_FEEDBACK = 0xa,
            // MScriptDescription "GetModifierOverrideAttackDamage"
            MODIFIER_PROPERTY_OVERRIDE_ATTACK_DAMAGE = 0xb,
            // MScriptDescription "GetModifierPreAttack"
            MODIFIER_PROPERTY_PRE_ATTACK = 0xc,
            // MScriptDescription "GetModifierInvisibilityLevel"
            MODIFIER_PROPERTY_INVISIBILITY_LEVEL = 0xd,
            // MScriptDescription "GetModifierInvisibilityAttackBehaviorException"
            MODIFIER_PROPERTY_INVISIBILITY_ATTACK_BEHAVIOR_EXCEPTION = 0xe,
            // MScriptDescription "GetModifierPersistentInvisibility"
            MODIFIER_PROPERTY_PERSISTENT_INVISIBILITY = 0xf,
            // MScriptDescription "GetModifierMoveSpeedBonus_Constant"
            MODIFIER_PROPERTY_MOVESPEED_BONUS_CONSTANT = 0x10,
            // MScriptDescription "GetModifierMoveSpeedOverride"
            MODIFIER_PROPERTY_MOVESPEED_BASE_OVERRIDE = 0x11,
            // MScriptDescription "GetModifierMoveSpeed_MinOverride"
            MODIFIER_PROPERTY_MOVESPEED_MIN_OVERRIDE = 0x12,
            // MScriptDescription "GetModifierMoveSpeed_MaxOverride"
            MODIFIER_PROPERTY_MOVESPEED_MAX_OVERRIDE = 0x13,
            // MScriptDescription "GetModifierMoveSpeedBonus_Percentage"
            MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE = 0x14,
            // MScriptDescription "GetModifierMoveSpeedBonus_Percentage_Unique"
            MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE_UNIQUE = 0x15,
            // MScriptDescription "GetModifierMoveSpeedBonus_Special_Boots"
            MODIFIER_PROPERTY_MOVESPEED_BONUS_UNIQUE = 0x16,
            // MScriptDescription "GetModifierMoveSpeedBonus_Special_Boots_2"
            MODIFIER_PROPERTY_MOVESPEED_BONUS_UNIQUE_2 = 0x17,
            // MScriptDescription "GetModifierMoveSpeedBonus_Constant_Unique"
            MODIFIER_PROPERTY_MOVESPEED_BONUS_CONSTANT_UNIQUE = 0x18,
            // MScriptDescription "GetModifierMoveSpeedBonus_Constant_Unique_2"
            MODIFIER_PROPERTY_MOVESPEED_BONUS_CONSTANT_UNIQUE_2 = 0x19,
            // MScriptDescription "GetModifierMoveSpeed_Absolute"
            MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE = 0x1a,
            // MScriptDescription "GetModifierMoveSpeed_AbsoluteMin"
            MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE_MIN = 0x1b,
            // MScriptDescription "GetModifierMoveSpeed_AbsoluteMax"
            MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE_MAX = 0x1c,
            // MScriptDescription "GetModifierIgnoreMovespeedLimit"
            MODIFIER_PROPERTY_IGNORE_MOVESPEED_LIMIT = 0x1d,
            // MScriptDescription "GetModifierMoveSpeed_Limit"
            MODIFIER_PROPERTY_MOVESPEED_LIMIT = 0x1e,
            // MScriptDescription "GetModifierAttackSpeedBaseOverride"
            MODIFIER_PROPERTY_ATTACKSPEED_BASE_OVERRIDE = 0x1f,
            // MScriptDescription "GetModifierFixedAttackRate"
            MODIFIER_PROPERTY_FIXED_ATTACK_RATE = 0x20,
            // MScriptDescription "GetModifierAttackSpeedBonus_Constant"
            MODIFIER_PROPERTY_ATTACKSPEED_BONUS_CONSTANT = 0x21,
            // MScriptDescription "GetModifierAttackSpeed_Limit"
            MODIFIER_PROPERTY_IGNORE_ATTACKSPEED_LIMIT = 0x22,
            // MScriptDescription "GetModifierCooldownReduction_Constant"
            MODIFIER_PROPERTY_COOLDOWN_REDUCTION_CONSTANT = 0x23,
            // MScriptDescription "GetModifierManacostReduction_Constant"
            MODIFIER_PROPERTY_MANACOST_REDUCTION_CONSTANT = 0x24,
            // MScriptDescription "GetModifierHealthcostReduction_Constant"
            MODIFIER_PROPERTY_HEALTHCOST_REDUCTION_CONSTANT = 0x25,
            // MScriptDescription "GetModifierBaseAttackTimeConstant"
            MODIFIER_PROPERTY_BASE_ATTACK_TIME_CONSTANT = 0x26,
            // MScriptDescription "GetModifierBaseAttackTimeConstant_Adjust"
            MODIFIER_PROPERTY_BASE_ATTACK_TIME_CONSTANT_ADJUST = 0x27,
            // MScriptDescription "GetModifierBaseAttackTimePercentage"
            MODIFIER_PROPERTY_BASE_ATTACK_TIME_PERCENTAGE = 0x28,
            // MScriptDescription "GetModifierAttackPointConstant"
            MODIFIER_PROPERTY_ATTACK_POINT_CONSTANT = 0x29,
            // MScriptDescription "GetModifierBonusDamageOutgoing_Percentage"
            MODIFIER_PROPERTY_BONUSDAMAGEOUTGOING_PERCENTAGE = 0x2a,
            // MScriptDescription "GetModifierDamageOutgoing_Percentage"
            MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE = 0x2b,
            // MScriptDescription "GetModifierDamageOutgoing_Percentage_Illusion"
            MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE_ILLUSION = 0x2c,
            // MScriptDescription "GetModifierDamageOutgoing_Percentage_Illusion_Amplify"
            MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE_ILLUSION_AMPLIFY = 0x2d,
            // MScriptDescription "GetModifierTotalDamageOutgoing_Percentage"
            MODIFIER_PROPERTY_TOTALDAMAGEOUTGOING_PERCENTAGE = 0x2e,
            // MScriptDescription "GetModifierSpellAmplify_Percentage"
            MODIFIER_PROPERTY_SPELL_AMPLIFY_PERCENTAGE = 0x2f,
            // MScriptDescription "GetModifierSpellAmplify_PercentageUnique"
            MODIFIER_PROPERTY_SPELL_AMPLIFY_PERCENTAGE_UNIQUE = 0x30,
            // MScriptDescription "GetModifierSpellAmplify_PercentageTarget"
            MODIFIER_PROPERTY_SPELL_AMPLIFY_PERCENTAGE_TARGET = 0x31,
            // MScriptDescription "GetModifierHealAmplify_PercentageSource"
            MODIFIER_PROPERTY_HEAL_AMPLIFY_PERCENTAGE_SOURCE = 0x32,
            // MScriptDescription "GetModifierHealAmplify_PercentageTarget"
            MODIFIER_PROPERTY_HEAL_AMPLIFY_PERCENTAGE_TARGET = 0x33,
            // MScriptDescription "GetModifierHPRegenAmplify_Percentage"
            MODIFIER_PROPERTY_HP_REGEN_AMPLIFY_PERCENTAGE = 0x34,
            // MScriptDescription "GetModifierLifestealRegenAmplify_Percentage"
            MODIFIER_PROPERTY_LIFESTEAL_AMPLIFY_PERCENTAGE = 0x35,
            // MScriptDescription "GetModifierSpellLifestealRegenAmplify_Percentage"
            MODIFIER_PROPERTY_SPELL_LIFESTEAL_AMPLIFY_PERCENTAGE = 0x36,
            // MScriptDescription "GetModifierSpellLifestealRegenAmplify_Percentage_Unique"
            MODIFIER_PROPERTY_SPELL_LIFESTEAL_AMPLIFY_PERCENTAGE_UNIQUE = 0x37,
            // MScriptDescription "GetModifierMPRegenAmplify_Percentage"
            MODIFIER_PROPERTY_MP_REGEN_AMPLIFY_PERCENTAGE = 0x38,
            // MScriptDescription "GetModifierMPRegenAmplify_Percentage_Unique"
            MODIFIER_PROPERTY_MP_REGEN_AMPLIFY_PERCENTAGE_UNIQUE = 0x39,
            // MScriptDescription "GetModifierManaDrainAmplify_Percentage"
            MODIFIER_PROPERTY_MANA_DRAIN_AMPLIFY_PERCENTAGE = 0x3a,
            // MScriptDescription "GetModifierMPRestoreAmplify_Percentage"
            MODIFIER_PROPERTY_MP_RESTORE_AMPLIFY_PERCENTAGE = 0x3b,
            // MScriptDescription "GetModifierBaseDamageOutgoing_Percentage"
            MODIFIER_PROPERTY_BASEDAMAGEOUTGOING_PERCENTAGE = 0x3c,
            // MScriptDescription "GetModifierBaseDamageOutgoing_PercentageUnique"
            MODIFIER_PROPERTY_BASEDAMAGEOUTGOING_PERCENTAGE_UNIQUE = 0x3d,
            // MScriptDescription "GetModifierIncomingDamage_Percentage"
            MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE = 0x3e,
            // MScriptDescription "GetModifierIncomingPhysicalDamage_Percentage"
            MODIFIER_PROPERTY_INCOMING_PHYSICAL_DAMAGE_PERCENTAGE = 0x3f,
            // MScriptDescription "GetModifierIncomingPhysicalDamageConstant"
            MODIFIER_PROPERTY_INCOMING_PHYSICAL_DAMAGE_CONSTANT = 0x40,
            // MScriptDescription "GetModifierIncomingSpellDamageConstant"
            MODIFIER_PROPERTY_INCOMING_SPELL_DAMAGE_CONSTANT = 0x41,
            // MScriptDescription "GetModifierEvasion_Constant"
            MODIFIER_PROPERTY_EVASION_CONSTANT = 0x42,
            // MScriptDescription "GetModifierNegativeEvasion_Constant"
            MODIFIER_PROPERTY_NEGATIVE_EVASION_CONSTANT = 0x43,
            // MScriptDescription "GetModifierStatusResistance"
            MODIFIER_PROPERTY_STATUS_RESISTANCE = 0x44,
            // MScriptDescription "GetModifierStatusResistanceStacking"
            MODIFIER_PROPERTY_STATUS_RESISTANCE_STACKING = 0x45,
            // MScriptDescription "GetModifierStatusResistanceCaster"
            MODIFIER_PROPERTY_STATUS_RESISTANCE_CASTER = 0x46,
            // MScriptDescription "GetModifierAvoidDamage"
            MODIFIER_PROPERTY_AVOID_DAMAGE = 0x47,
            // MScriptDescription "GetModifierAvoidSpell"
            MODIFIER_PROPERTY_AVOID_SPELL = 0x48,
            // MScriptDescription "GetModifierMiss_Percentage"
            MODIFIER_PROPERTY_MISS_PERCENTAGE = 0x49,
            // MScriptDescription "GetModifierPhysicalArmorBase_Percentage"
            MODIFIER_PROPERTY_PHYSICAL_ARMOR_BASE_PERCENTAGE = 0x4a,
            // MScriptDescription "GetModifierPhysicalArmorTotal_Percentage"
            MODIFIER_PROPERTY_PHYSICAL_ARMOR_TOTAL_PERCENTAGE = 0x4b,
            // MScriptDescription "GetModifierPhysicalArmorBonus"
            MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS = 0x4c,
            // MScriptDescription "GetModifierPhysicalArmorBonusUnique"
            MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS_UNIQUE = 0x4d,
            // MScriptDescription "GetModifierPhysicalArmorBonusUniqueActive"
            MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS_UNIQUE_ACTIVE = 0x4e,
            // MScriptDescription "GetModifierPhysicalArmorBonusPost"
            MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS_POST = 0x4f,
            // MScriptDescription "GetModifierMinPhysicalArmor"
            MODIFIER_PROPERTY_MIN_PHYSICAL_ARMOR = 0x50,
            // MScriptDescription "GetModifierIgnorePhysicalArmor"
            MODIFIER_PROPERTY_IGNORE_PHYSICAL_ARMOR = 0x51,
            // MScriptDescription "GetModifierMagicalResistanceBaseReduction"
            MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BASE_REDUCTION = 0x52,
            // MScriptDescription "GetModifierMagicalResistanceDirectModification"
            MODIFIER_PROPERTY_MAGICAL_RESISTANCE_DIRECT_MODIFICATION = 0x53,
            // MScriptDescription "GetModifierMagicalResistanceBonus"
            MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BONUS = 0x54,
            // MScriptDescription "GetModifierMagicalResistanceBonusIllusions"
            MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BONUS_ILLUSIONS = 0x55,
            // MScriptDescription "GetModifierMagicalResistanceBonusUnique"
            MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BONUS_UNIQUE = 0x56,
            // MScriptDescription "GetModifierMagicalResistanceDecrepifyUnique"
            MODIFIER_PROPERTY_MAGICAL_RESISTANCE_DECREPIFY_UNIQUE = 0x57,
            // MScriptDescription "GetModifierBaseRegen"
            MODIFIER_PROPERTY_BASE_MANA_REGEN = 0x58,
            // MScriptDescription "GetModifierConstantManaRegen"
            MODIFIER_PROPERTY_MANA_REGEN_CONSTANT = 0x59,
            // MScriptDescription "GetModifierConstantManaRegenUnique"
            MODIFIER_PROPERTY_MANA_REGEN_CONSTANT_UNIQUE = 0x5a,
            // MScriptDescription "GetModifierTotalPercentageManaRegen"
            MODIFIER_PROPERTY_MANA_REGEN_TOTAL_PERCENTAGE = 0x5b,
            // MScriptDescription "GetModifierConstantHealthRegen"
            MODIFIER_PROPERTY_HEALTH_REGEN_CONSTANT = 0x5c,
            // MScriptDescription "GetModifierHealthRegenPercentage"
            MODIFIER_PROPERTY_HEALTH_REGEN_PERCENTAGE = 0x5d,
            // MScriptDescription "GetModifierHealthRegenPercentageUnique"
            MODIFIER_PROPERTY_HEALTH_REGEN_PERCENTAGE_UNIQUE = 0x5e,
            // MScriptDescription "GetModifierHealthBonus"
            MODIFIER_PROPERTY_HEALTH_BONUS = 0x5f,
            // MScriptDescription "GetModifierManaBonus"
            MODIFIER_PROPERTY_MANA_BONUS = 0x60,
            // MScriptDescription "GetModifierExtraStrengthBonus"
            MODIFIER_PROPERTY_EXTRA_STRENGTH_BONUS = 0x61,
            // MScriptDescription "GetModifierExtraHealthBonus"
            MODIFIER_PROPERTY_EXTRA_HEALTH_BONUS = 0x62,
            // MScriptDescription "GetModifierExtraManaBonus"
            MODIFIER_PROPERTY_EXTRA_MANA_BONUS = 0x63,
            // MScriptDescription "GetModifierExtraManaBonusPercentage"
            MODIFIER_PROPERTY_EXTRA_MANA_BONUS_PERCENTAGE = 0x64,
            // MScriptDescription "GetModifierExtraHealthPercentage"
            MODIFIER_PROPERTY_EXTRA_HEALTH_PERCENTAGE = 0x65,
            // MScriptDescription "GetModifierExtraManaPercentage"
            MODIFIER_PROPERTY_EXTRA_MANA_PERCENTAGE = 0x66,
            // MScriptDescription "GetModifierBonusStats_Strength"
            MODIFIER_PROPERTY_STATS_STRENGTH_BONUS = 0x67,
            // MScriptDescription "GetModifierBonusStats_Agility"
            MODIFIER_PROPERTY_STATS_AGILITY_BONUS = 0x68,
            // MScriptDescription "GetModifierBonusStats_Intellect"
            MODIFIER_PROPERTY_STATS_INTELLECT_BONUS = 0x69,
            // MScriptDescription "GetModifierBonusStats_Strength_Percentage"
            MODIFIER_PROPERTY_STATS_STRENGTH_BONUS_PERCENTAGE = 0x6a,
            // MScriptDescription "GetModifierBonusStats_Agility_Percentage"
            MODIFIER_PROPERTY_STATS_AGILITY_BONUS_PERCENTAGE = 0x6b,
            // MScriptDescription "GetModifierBonusStats_Intellect_Percentage"
            MODIFIER_PROPERTY_STATS_INTELLECT_BONUS_PERCENTAGE = 0x6c,
            // MScriptDescription "GetModifierIntellectNone"
            MODIFIER_PROPERTY_STATS_INTELLECT_NONE = 0x6d,
            // MScriptDescription "GetModifierCastRangeBonus"
            MODIFIER_PROPERTY_CAST_RANGE_BONUS = 0x6e,
            // MScriptDescription "GetModifierCastRangeBonusPercentage"
            MODIFIER_PROPERTY_CAST_RANGE_BONUS_PERCENTAGE = 0x6f,
            // MScriptDescription "GetModifierCastRangeBonusTarget"
            MODIFIER_PROPERTY_CAST_RANGE_BONUS_TARGET = 0x70,
            // MScriptDescription "GetModifierCastRangeBonusStacking"
            MODIFIER_PROPERTY_CAST_RANGE_BONUS_STACKING = 0x71,
            // MScriptDescription "GetModifierAttackRangeOverride"
            MODIFIER_PROPERTY_ATTACK_RANGE_BASE_OVERRIDE = 0x72,
            // MScriptDescription "GetModifierAttackRangeBonus"
            MODIFIER_PROPERTY_ATTACK_RANGE_BONUS = 0x73,
            // MScriptDescription "GetModifierAttackRangeBonusUnique"
            MODIFIER_PROPERTY_ATTACK_RANGE_BONUS_UNIQUE = 0x74,
            // MScriptDescription "GetModifierAttackRangeBonusPercentage"
            MODIFIER_PROPERTY_ATTACK_RANGE_BONUS_PERCENTAGE = 0x75,
            // MScriptDescription "GetModifierMaxAttackRange"
            MODIFIER_PROPERTY_MAX_ATTACK_RANGE = 0x76,
            // MScriptDescription "GetModifierProjectileSpeedBonus"
            MODIFIER_PROPERTY_PROJECTILE_SPEED_BONUS = 0x77,
            // MScriptDescription "GetModifierProjectileSpeedBonusPercentage"
            MODIFIER_PROPERTY_PROJECTILE_SPEED_BONUS_PERCENTAGE = 0x78,
            // MScriptDescription "GetModifierProjectileName"
            MODIFIER_PROPERTY_PROJECTILE_NAME = 0x79,
            // MScriptDescription "ReincarnateTime"
            MODIFIER_PROPERTY_REINCARNATION = 0x7a,
            // MScriptDescription "ReincarnateSuppressFX"
            MODIFIER_PROPERTY_REINCARNATION_SUPPRESS_FX = 0x7b,
            // MScriptDescription "GetModifierConstantRespawnTime"
            MODIFIER_PROPERTY_RESPAWNTIME = 0x7c,
            // MScriptDescription "GetModifierPercentageRespawnTime"
            MODIFIER_PROPERTY_RESPAWNTIME_PERCENTAGE = 0x7d,
            // MScriptDescription "GetModifierStackingRespawnTime"
            MODIFIER_PROPERTY_RESPAWNTIME_STACKING = 0x7e,
            // MScriptDescription "GetModifierPercentageCooldown"
            MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE = 0x7f,
            // MScriptDescription "GetModifierPercentageCooldownOngoing"
            MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE_ONGOING = 0x80,
            // MScriptDescription "GetModifierPercentageCasttime"
            MODIFIER_PROPERTY_CASTTIME_PERCENTAGE = 0x81,
            // MScriptDescription "GetModifierConstantCasttime"
            MODIFIER_PROPERTY_CASTTIME_CONSTANT = 0x82,
            // MScriptDescription "GetModifierPercentageAttackAnimTime"
            MODIFIER_PROPERTY_ATTACK_ANIM_TIME_PERCENTAGE = 0x83,
            // MScriptDescription "GetModifierPercentageManacost"
            MODIFIER_PROPERTY_MANACOST_PERCENTAGE = 0x84,
            // MScriptDescription "GetModifierPercentageManacostStacking"
            MODIFIER_PROPERTY_MANACOST_PERCENTAGE_STACKING = 0x85,
            // MScriptDescription "GetModifierPercentageHealthcost"
            MODIFIER_PROPERTY_HEALTHCOST_PERCENTAGE = 0x86,
            // MScriptDescription "GetModifierPercentageHealthcostStacking"
            MODIFIER_PROPERTY_HEALTHCOST_PERCENTAGE_STACKING = 0x87,
            // MScriptDescription "GetModifierConstantDeathGoldCost"
            MODIFIER_PROPERTY_DEATHGOLDCOST = 0x88,
            // MScriptDescription "GetModifierPercentageDeathGoldCost"
            MODIFIER_PROPERTY_PERCENTAGE_DEATHGOLDCOST = 0x89,
            // MScriptDescription "GetModifierPercentageExpRateBoost"
            MODIFIER_PROPERTY_EXP_RATE_BOOST = 0x8a,
            // MScriptDescription "GetModifierPercentageGoldRateBoost"
            MODIFIER_PROPERTY_GOLD_RATE_BOOST = 0x8b,
            // MScriptDescription "GetModifierPercentageKillAssistGoldBoost"
            MODIFIER_PROPERTY_KILL_ASSIST_GOLD_BOOST = 0x8c,
            // MScriptDescription "GetModifierPercentageConvertExpToGold"
            MODIFIER_PROPERTY_CONVERT_EXP_TO_GOLD_PCT = 0x8d,
            // MScriptDescription "GetModifierPreAttack_CriticalStrike"
            MODIFIER_PROPERTY_PREATTACK_CRITICALSTRIKE = 0x8e,
            // MScriptDescription "GetModifierPreAttack_Target_CriticalStrike"
            MODIFIER_PROPERTY_PREATTACK_TARGET_CRITICALSTRIKE = 0x8f,
            // MScriptDescription "GetModifierMagical_ConstantBlock"
            MODIFIER_PROPERTY_MAGICAL_CONSTANT_BLOCK = 0x90,
            // MScriptDescription "GetModifierPhysical_ConstantBlock"
            MODIFIER_PROPERTY_PHYSICAL_CONSTANT_BLOCK = 0x91,
            // MScriptDescription "GetModifierPhysical_ConstantBlockSpecial"
            MODIFIER_PROPERTY_PHYSICAL_CONSTANT_BLOCK_SPECIAL = 0x92,
            // MScriptDescription "GetModifierPhysical_ConstantBlockBonus"
            MODIFIER_PROPERTY_PHYSICAL_CONSTANT_BLOCK_BONUS = 0x93,
            // MScriptDescription "GetModifierInnateDamageBlockPctOverride"
            MODIFIER_PROPERTY_INNATE_DAMAGE_BLOCK_PCT_OVERRIDE = 0x94,
            // MScriptDescription "GetModifierPhysical_ConstantBlockUnavoidablePreArmor"
            MODIFIER_PROPERTY_TOTAL_CONSTANT_BLOCK_UNAVOIDABLE_PRE_ARMOR = 0x95,
            // MScriptDescription "GetModifierTotal_ConstantBlock"
            MODIFIER_PROPERTY_TOTAL_CONSTANT_BLOCK = 0x96,
            // MScriptDescription "GetOverrideAnimation"
            MODIFIER_PROPERTY_OVERRIDE_ANIMATION = 0x97,
            // MScriptDescription "GetOverrideAnimationRate"
            MODIFIER_PROPERTY_OVERRIDE_ANIMATION_RATE = 0x98,
            // MScriptDescription "GetAbsorbSpell"
            MODIFIER_PROPERTY_ABSORB_SPELL = 0x99,
            // MScriptDescription "GetReflectSpell"
            MODIFIER_PROPERTY_REFLECT_SPELL = 0x9a,
            // MScriptDescription "GetDisableAutoAttack"
            MODIFIER_PROPERTY_DISABLE_AUTOATTACK = 0x9b,
            // MScriptDescription "GetBonusDayVision"
            MODIFIER_PROPERTY_BONUS_DAY_VISION = 0x9c,
            // MScriptDescription "GetBonusDayVisionPercentage"
            MODIFIER_PROPERTY_BONUS_DAY_VISION_PERCENTAGE = 0x9d,
            // MScriptDescription "GetBonusNightVision"
            MODIFIER_PROPERTY_BONUS_NIGHT_VISION = 0x9e,
            // MScriptDescription "GetBonusNightVisionUnique"
            MODIFIER_PROPERTY_BONUS_NIGHT_VISION_UNIQUE = 0x9f,
            // MScriptDescription "GetBonusVisionPercentage"
            MODIFIER_PROPERTY_BONUS_VISION_PERCENTAGE = 0xa0,
            // MScriptDescription "GetFixedDayVision"
            MODIFIER_PROPERTY_FIXED_DAY_VISION = 0xa1,
            // MScriptDescription "GetFixedNightVision"
            MODIFIER_PROPERTY_FIXED_NIGHT_VISION = 0xa2,
            // MScriptDescription "GetMinHealth"
            MODIFIER_PROPERTY_MIN_HEALTH = 0xa3,
            // MScriptDescription "GetMinMana"
            MODIFIER_PROPERTY_MIN_MANA = 0xa4,
            // MScriptDescription "GetAbsoluteNoDamagePhysical"
            MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_PHYSICAL = 0xa5,
            // MScriptDescription "GetAbsoluteNoDamageMagical"
            MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_MAGICAL = 0xa6,
            // MScriptDescription "GetAbsoluteNoDamagePure"
            MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_PURE = 0xa7,
            // MScriptDescription "GetIsIllusion"
            MODIFIER_PROPERTY_IS_ILLUSION = 0xa8,
            // MScriptDescription "GetModifierIllusionLabel"
            MODIFIER_PROPERTY_ILLUSION_LABEL = 0xa9,
            // MScriptDescription "GetModifierStrongIllusion"
            MODIFIER_PROPERTY_STRONG_ILLUSION = 0xaa,
            // MScriptDescription "GetModifierSuperIllusion"
            MODIFIER_PROPERTY_SUPER_ILLUSION = 0xab,
            // MScriptDescription "GetModifierSuperIllusionWithUltimate"
            MODIFIER_PROPERTY_SUPER_ILLUSION_WITH_ULTIMATE = 0xac,
            // MScriptDescription "GetModifierXPDuringDeath"
            MODIFIER_PROPERTY_XP_DURING_DEATH = 0xad,
            // MScriptDescription "GetModifierTurnRate_Percentage"
            MODIFIER_PROPERTY_TURN_RATE_PERCENTAGE = 0xae,
            // MScriptDescription "GetModifierTurnRate_Override"
            MODIFIER_PROPERTY_TURN_RATE_OVERRIDE = 0xaf,
            // MScriptDescription "GetDisableHealing"
            MODIFIER_PROPERTY_DISABLE_HEALING = 0xb0,
            // MScriptDescription "GetDisableManaGain"
            MODIFIER_PROPERTY_DISABLE_MANA_GAIN = 0xb1,
            // MScriptDescription "GetAlwaysAllowAttack"
            MODIFIER_PROPERTY_ALWAYS_ALLOW_ATTACK = 0xb2,
            // MScriptDescription "GetAllowEtherealAttack"
            MODIFIER_PROPERTY_ALWAYS_ETHEREAL_ATTACK = 0xb3,
            // MScriptDescription "GetOverrideAttackMagical"
            MODIFIER_PROPERTY_OVERRIDE_ATTACK_MAGICAL = 0xb4,
            // MScriptDescription "GetModifierUnitStatsNeedsRefresh"
            MODIFIER_PROPERTY_UNIT_STATS_NEEDS_REFRESH = 0xb5,
            // MScriptDescription "Unused"
            MODIFIER_PROPERTY_BOUNTY_CREEP_MULTIPLIER = 0xb6,
            // MScriptDescription "Unused"
            MODIFIER_PROPERTY_BOUNTY_OTHER_MULTIPLIER = 0xb7,
            // MScriptDescription "GetModifierUnitDisllowUpgrading"
            MODIFIER_PROPERTY_UNIT_DISALLOW_UPGRADING = 0xb8,
            // MScriptDescription "GetModifierDodgeProjectile"
            MODIFIER_PROPERTY_DODGE_PROJECTILE = 0xb9,
            // MScriptDescription "GetTriggerCosmeticAndEndAttack"
            MODIFIER_PROPERTY_TRIGGER_COSMETIC_AND_END_ATTACK = 0xba,
            // MScriptDescription "GetPrimaryStatDamageMultiplier"
            MODIFIER_PROPERTY_PRIMARY_STAT_DAMAGE_MULTIPLIER = 0xbb,
            // MScriptDescription "GetModifierPreAttack_DeadlyBlow"
            MODIFIER_PROPERTY_PREATTACK_DEADLY_BLOW = 0xbc,
            // MScriptDescription "GetAlwaysAutoAttackWhileHoldPosition"
            MODIFIER_PROPERTY_ALWAYS_AUTOATTACK_WHILE_HOLD_POSITION = 0xbd,
            // MScriptDescription "GetPhysicalArmorPiercingPercentageTarget"
            MODIFIER_PROPERTY_PHYSICAL_ARMOR_PIERCING_PERCENTAGE_TARGET = 0xbe,
            // MScriptDescription "GetMagicalArmorPiercingPercentageTarget"
            MODIFIER_PROPERTY_MAGICAL_ARMOR_PIERCING_PERCENTAGE_TARGET = 0xbf,
            // MScriptDescription "GetCriticalStrikeBonus"
            MODIFIER_PROPERTY_CRITICAL_STRIKE_BONUS = 0xc0,
            // MScriptDescription "GetConvertAttackPhysicalToPure"
            MODIFIER_PROPERTY_CONVERT_ATTACK_PHYSICAL_TO_PURE = 0xc1,
            // MScriptDescription "GetBuffAmplification"
            MODIFIER_PROPERTY_BUFF_AMPLIFICATION = 0xc2,
            // MScriptDescription "OnSpellTargetReady"
            MODIFIER_EVENT_ON_SPELL_TARGET_READY = 0xc3,
            // MScriptDescription "OnAttackRecord"
            MODIFIER_EVENT_ON_ATTACK_RECORD = 0xc4,
            // MScriptDescription "OnAttackStart"
            MODIFIER_EVENT_ON_ATTACK_START = 0xc5,
            // MScriptDescription "OnAttack"
            MODIFIER_EVENT_ON_ATTACK = 0xc6,
            // MScriptDescription "OnAttackLanded"
            MODIFIER_EVENT_ON_ATTACK_LANDED = 0xc7,
            // MScriptDescription "OnAttackFail"
            MODIFIER_EVENT_ON_ATTACK_FAIL = 0xc8,
            // MScriptDescription "OnAttackAllied"
            MODIFIER_EVENT_ON_ATTACK_ALLIED = 0xc9,
            // MScriptDescription "OnProjectileDodge"
            MODIFIER_EVENT_ON_PROJECTILE_DODGE = 0xca,
            // MScriptDescription "OnOrder"
            MODIFIER_EVENT_ON_ORDER = 0xcb,
            // MScriptDescription "OnOrderReceived"
            MODIFIER_EVENT_ON_ORDER_RECEIVED = 0xcc,
            // MScriptDescription "OnUnitMoved"
            MODIFIER_EVENT_ON_UNIT_MOVED = 0xcd,
            // MScriptDescription "OnAbilityStart"
            MODIFIER_EVENT_ON_ABILITY_START = 0xce,
            // MScriptDescription "OnAbilityExecuted"
            MODIFIER_EVENT_ON_ABILITY_EXECUTED = 0xcf,
            // MScriptDescription "OnAbilityFullyCast"
            MODIFIER_EVENT_ON_ABILITY_FULLY_CAST = 0xd0,
            // MScriptDescription "OnBreakInvisibility"
            MODIFIER_EVENT_ON_BREAK_INVISIBILITY = 0xd1,
            // MScriptDescription "OnAbilityEndChannel"
            MODIFIER_EVENT_ON_ABILITY_END_CHANNEL = 0xd2,
            // MScriptDescription "Unused"
            MODIFIER_EVENT_ON_PROCESS_UPGRADE = 0xd3,
            // MScriptDescription "Unused"
            MODIFIER_EVENT_ON_REFRESH = 0xd4,
            // MScriptDescription "OnTakeDamage"
            MODIFIER_EVENT_ON_TAKEDAMAGE = 0xd5,
            // MScriptDescription "OnDamagePrevented"
            MODIFIER_EVENT_ON_DEATH_PREVENTED = 0xd6,
            // MScriptDescription "OnStateChanged"
            MODIFIER_EVENT_ON_STATE_CHANGED = 0xd7,
            // MScriptDescription "Unused"
            MODIFIER_EVENT_ON_ORB_EFFECT = 0xd8,
            // MScriptDescription "OnProcessCleave"
            MODIFIER_EVENT_ON_PROCESS_CLEAVE = 0xd9,
            // MScriptDescription "OnDamageCalculated"
            MODIFIER_EVENT_ON_DAMAGE_CALCULATED = 0xda,
            // MScriptDescription "OnMagicDamageCalculated"
            MODIFIER_EVENT_ON_MAGIC_DAMAGE_CALCULATED = 0xdb,
            // MScriptDescription "OnAttacked"
            MODIFIER_EVENT_ON_ATTACKED = 0xdc,
            // MScriptDescription "OnDeath"
            MODIFIER_EVENT_ON_DEATH = 0xdd,
            // MScriptDescription "OnDeathCompleted"
            MODIFIER_EVENT_ON_DEATH_COMPLETED = 0xde,
            // MScriptDescription "OnRespawn"
            MODIFIER_EVENT_ON_RESPAWN = 0xdf,
            // MScriptDescription "OnSpentMana"
            MODIFIER_EVENT_ON_SPENT_MANA = 0xe0,
            // MScriptDescription "OnSpentHealth"
            MODIFIER_EVENT_ON_SPENT_HEALTH = 0xe1,
            // MScriptDescription "OnSpentItemCharge"
            MODIFIER_EVENT_ON_SPENT_ITEM_CHARGE = 0xe2,
            // MScriptDescription "OnTeleporting"
            MODIFIER_EVENT_ON_TELEPORTING = 0xe3,
            // MScriptDescription "OnTeleported"
            MODIFIER_EVENT_ON_TELEPORTED = 0xe4,
            // MScriptDescription "OnSetLocation"
            MODIFIER_EVENT_ON_SET_LOCATION = 0xe5,
            // MScriptDescription "OnHealthGained"
            MODIFIER_EVENT_ON_HEALTH_GAINED = 0xe6,
            // MScriptDescription "OnManaGained"
            MODIFIER_EVENT_ON_MANA_GAINED = 0xe7,
            // MScriptDescription "OnTakeDamageKillCredit"
            MODIFIER_EVENT_ON_TAKEDAMAGE_KILLCREDIT = 0xe8,
            // MScriptDescription "OnHeroKilled"
            MODIFIER_EVENT_ON_HERO_KILLED = 0xe9,
            // MScriptDescription "OnHealReceived"
            MODIFIER_EVENT_ON_HEAL_RECEIVED = 0xea,
            // MScriptDescription "OnRedirectHealthGain"
            MODIFIER_EVENT_ON_REDIRECT_HEALTH_GAIN = 0xeb,
            // MScriptDescription "OnBuildingKilled"
            MODIFIER_EVENT_ON_BUILDING_KILLED = 0xec,
            // MScriptDescription "OnModelChanged"
            MODIFIER_EVENT_ON_MODEL_CHANGED = 0xed,
            // MScriptDescription "OnModifierAdded"
            MODIFIER_EVENT_ON_MODIFIER_ADDED = 0xee,
            // MScriptDescription "OnModifierRemoved"
            MODIFIER_EVENT_ON_MODIFIER_REMOVED = 0xef,
            // MScriptDescription "OnScepterUpgradeSelected"
            MODIFIER_EVENT_ON_SCEPTER_UPGRADE_SELECTED = 0xf0,
            // MScriptDescription "OnShardUpgradeSelected"
            MODIFIER_EVENT_ON_SHARD_UPGRADE_SELECTED = 0xf1,
            // MScriptDescription "OnTooltip"
            MODIFIER_PROPERTY_TOOLTIP = 0xf2,
            // MScriptDescription "GetModifierModelChange"
            MODIFIER_PROPERTY_MODEL_CHANGE = 0xf3,
            // MScriptDescription "GetModifierModelScale"
            MODIFIER_PROPERTY_MODEL_SCALE = 0xf4,
            // MScriptDescription "GetModifierModelScaleAnimateTime"
            MODIFIER_PROPERTY_MODEL_SCALE_ANIMATE_TIME = 0xf5,
            // MScriptDescription "GetModifierModelScaleUseInOutEase"
            MODIFIER_PROPERTY_MODEL_SCALE_USE_IN_OUT_EASE = 0xf6,
            // MScriptDescription "GetModifierModelScaleConstant"
            MODIFIER_PROPERTY_MODEL_SCALE_CONSTANT = 0xf7,
            // MScriptDescription "GetModifierScepter"
            MODIFIER_PROPERTY_IS_SCEPTER = 0xf8,
            // MScriptDescription "GetModifierShard"
            MODIFIER_PROPERTY_IS_SHARD = 0xf9,
            // MScriptDescription "GetModifierRadarCooldownReduction"
            MODIFIER_PROPERTY_RADAR_COOLDOWN_REDUCTION = 0xfa,
            // MScriptDescription "GetActivityTranslationModifiers"
            MODIFIER_PROPERTY_TRANSLATE_ACTIVITY_MODIFIERS = 0xfb,
            // MScriptDescription "GetAttackSound"
            MODIFIER_PROPERTY_TRANSLATE_ATTACK_SOUND = 0xfc,
            // MScriptDescription "GetUnitLifetimeFraction"
            MODIFIER_PROPERTY_LIFETIME_FRACTION = 0xfd,
            // MScriptDescription "GetModifierProvidesFOWVision"
            MODIFIER_PROPERTY_PROVIDES_FOW_POSITION = 0xfe,
            // MScriptDescription "GetModifierSpellsRequireHP"
            MODIFIER_PROPERTY_SPELLS_REQUIRE_HP = 0xff,
            // MScriptDescription "GetModifierConvertManaCostToHealthCost"
            MODIFIER_PROPERTY_CONVERT_MANA_COST_TO_HEALTH_COST = 0x100,
            // MScriptDescription "GetForceDrawOnMinimap"
            MODIFIER_PROPERTY_FORCE_DRAW_MINIMAP = 0x101,
            // MScriptDescription "GetModifierDisableTurning"
            MODIFIER_PROPERTY_DISABLE_TURNING = 0x102,
            // MScriptDescription "GetModifierIgnoreCastAngle"
            MODIFIER_PROPERTY_IGNORE_CAST_ANGLE = 0x103,
            // MScriptDescription "GetModifierChangeAbilityValue"
            MODIFIER_PROPERTY_CHANGE_ABILITY_VALUE = 0x104,
            // MScriptDescription "GetModifierOverrideAbilitySpecial"
            MODIFIER_PROPERTY_OVERRIDE_ABILITY_SPECIAL = 0x105,
            // MScriptDescription "GetModifierOverrideAbilitySpecialValue"
            MODIFIER_PROPERTY_OVERRIDE_ABILITY_SPECIAL_VALUE = 0x106,
            // MScriptDescription "GetModifierAbilityLayout"
            MODIFIER_PROPERTY_ABILITY_LAYOUT = 0x107,
            // MScriptDescription "OnDominated"
            MODIFIER_EVENT_ON_DOMINATED = 0x108,
            // MScriptDescription "OnKill"
            MODIFIER_EVENT_ON_KILL = 0x109,
            // MScriptDescription "OnAssist"
            MODIFIER_EVENT_ON_ASSIST = 0x10a,
            // MScriptDescription "GetModifierTempestDouble"
            MODIFIER_PROPERTY_TEMPEST_DOUBLE = 0x10b,
            // MScriptDescription "PreserveParticlesOnModelChanged"
            MODIFIER_PROPERTY_PRESERVE_PARTICLES_ON_MODEL_CHANGE = 0x10c,
            // MScriptDescription "OnAttackFinished"
            MODIFIER_EVENT_ON_ATTACK_FINISHED = 0x10d,
            // MScriptDescription "GetModifierIgnoreCooldown"
            MODIFIER_PROPERTY_IGNORE_COOLDOWN = 0x10e,
            // MScriptDescription "GetModifierCanAttackTrees"
            MODIFIER_PROPERTY_CAN_ATTACK_TREES = 0x10f,
            // MScriptDescription "GetVisualZDelta"
            MODIFIER_PROPERTY_VISUAL_Z_DELTA = 0x110,
            // MScriptDescription "GetVisualZSpeedBaseOverride"
            MODIFIER_PROPERTY_VISUAL_Z_SPEED_BASE_OVERRIDE = 0x111,
            // MScriptDescription
            MODIFIER_PROPERTY_INCOMING_DAMAGE_ILLUSION = 0x112,
            // MScriptDescription "GetModifierNoVisionOfAttacker"
            MODIFIER_PROPERTY_DONT_GIVE_VISION_OF_ATTACKER = 0x113,
            // MScriptDescription "OnTooltip2"
            MODIFIER_PROPERTY_TOOLTIP2 = 0x114,
            // MScriptDescription "OnAttackRecordDestroy"
            MODIFIER_EVENT_ON_ATTACK_RECORD_DESTROY = 0x115,
            // MScriptDescription "OnProjectileObstructionHit"
            MODIFIER_EVENT_ON_PROJECTILE_OBSTRUCTION_HIT = 0x116,
            // MScriptDescription "GetSuppressTeleport"
            MODIFIER_PROPERTY_SUPPRESS_TELEPORT = 0x117,
            // MScriptDescription "OnAttackCancelled"
            MODIFIER_EVENT_ON_ATTACK_CANCELLED = 0x118,
            // MScriptDescription "GetSuppressCleave"
            MODIFIER_PROPERTY_SUPPRESS_CLEAVE = 0x119,
            // MScriptDescription "BotAttackScoreBonus"
            MODIFIER_PROPERTY_BOT_ATTACK_SCORE_BONUS = 0x11a,
            // MScriptDescription "GetModifierAttackSpeedReductionPercentage"
            MODIFIER_PROPERTY_ATTACKSPEED_REDUCTION_PERCENTAGE = 0x11b,
            // MScriptDescription "GetModifierMoveSpeedReductionPercentage"
            MODIFIER_PROPERTY_MOVESPEED_REDUCTION_PERCENTAGE = 0x11c,
            // MScriptDescription
            MODIFIER_PROPERTY_ATTACK_WHILE_MOVING_TARGET = 0x11d,
            // MScriptDescription "GetModifierAttackSpeedPercentage"
            MODIFIER_PROPERTY_ATTACKSPEED_PERCENTAGE = 0x11e,
            // MScriptDescription "OnAttemptProjectileDodge"
            MODIFIER_EVENT_ON_ATTEMPT_PROJECTILE_DODGE = 0x11f,
            // MScriptDescription "GetModifierPercentageCooldownStacking"
            MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE_STACKING = 0x120,
            // MScriptDescription "GetModifierSpellRedirectTarget"
            MODIFIER_PROPERTY_SPELL_REDIRECT_TARGET = 0x121,
            // MScriptDescription "GetModifierTurnRateConstant"
            MODIFIER_PROPERTY_TURN_RATE_CONSTANT = 0x122,
            // MScriptDescription "GetModifierIsPackRat"
            MODIFIER_PROPERTY_PACK_RAT = 0x123,
            // MScriptDescription "GetModifierPhysicalDamageOutgoing_Percentage"
            MODIFIER_PROPERTY_PHYSICALDAMAGEOUTGOING_PERCENTAGE = 0x124,
            // MScriptDescription "GetModifierKnockbackAmplification_Percentage"
            MODIFIER_PROPERTY_KNOCKBACK_AMPLIFICATION_PERCENTAGE = 0x125,
            // MScriptDescription "GetModifierHealthBarPips"
            MODIFIER_PROPERTY_HEALTHBAR_PIPS = 0x126,
            // MScriptDescription "GetModifierIncomingDamageConstant"
            MODIFIER_PROPERTY_INCOMING_DAMAGE_CONSTANT = 0x127,
            // MScriptDescription "OnSpellAppliedSuccessfully"
            MODIFIER_EVENT_SPELL_APPLIED_SUCCESSFULLY = 0x128,
            // MScriptDescription "GetModifierAvoidDamageAfterReductions"
            MODIFIER_PROPERTY_AVOID_DAMAGE_AFTER_REDUCTIONS = 0x129,
            // MScriptDescription "GetModifierPropetyFailAttack"
            MODIFIER_PROPERTY_FAIL_ATTACK = 0x12a,
            // MScriptDescription "GetModifierPrereduceIncomingDamage_Mult"
            MODIFIER_PROPERTY_PREREDUCE_INCOMING_DAMAGE_MULT = 0x12b,
            // MScriptDescription "GetModifierSuppressFullscreenDeathFX"
            MODIFIER_PROPERTY_SUPPRESS_FULLSCREEN_DEATH_FX = 0x12c,
            // MScriptDescription "MODIFIER_PROPERTY_INCOMING_DAMAGE_CONSTANT_POST"
            MODIFIER_PROPERTY_INCOMING_DAMAGE_CONSTANT_POST = 0x12d,
            // MScriptDescription "GetModifierDamageOutgoing_PercentageMultiplicative"
            MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE_MULTIPLICATIVE = 0x12e,
            // MScriptDescription "GetModifierTickGold_Multiplier"
            MODIFIER_PROPERTY_TICK_GOLD_MULTIPLIER = 0x12f,
            // MScriptDescription "GEtModifierSlowResistance_Unique"
            MODIFIER_PROPERTY_SLOW_RESISTANCE_UNIQUE = 0x130,
            // MScriptDescription "GetModifierSlowResistance_Stacking"
            MODIFIER_PROPERTY_SLOW_RESISTANCE_STACKING = 0x131,
            // MScriptDescription "GetModifierSlowResistanceAppliesToAttacks"
            MODIFIER_PROPERTY_SLOW_RESISTANCE_APPLIES_TO_ATTACKS = 0x132,
            // MScriptDescription "GetModifierAoEBonusPercentage"
            MODIFIER_PROPERTY_AOE_BONUS_PERCENTAGE = 0x133,
            // MScriptDescription "GetModifierProjectileSpeed"
            MODIFIER_PROPERTY_PROJECTILE_SPEED = 0x134,
            // MScriptDescription "GetModifierProjectileSpeedTarget"
            MODIFIER_PROPERTY_PROJECTILE_SPEED_TARGET = 0x135,
            // MScriptDescription "GetModifierBecomeStrength"
            MODIFIER_PROPERTY_BECOME_STRENGTH = 0x136,
            // MScriptDescription "GetModifierBecomeAgility"
            MODIFIER_PROPERTY_BECOME_AGILITY = 0x137,
            // MScriptDescription "GetModifierBecomeIntelligence"
            MODIFIER_PROPERTY_BECOME_INTELLIGENCE = 0x138,
            // MScriptDescription "GetModifierBecomeUniversal"
            MODIFIER_PROPERTY_BECOME_UNIVERSAL = 0x139,
            // MScriptDescription "OnForceProcMagicStick"
            MODIFIER_EVENT_ON_FORCE_PROC_MAGIC_STICK = 0x13a,
            // MScriptDescription "OnDamageHPLoss"
            MODIFIER_EVENT_ON_DAMAGE_HPLOSS = 0x13b,
            // MScriptDescription "GetModifierShareXPRune"
            MODIFIER_PROPERTY_SHARE_XPRUNE = 0x13c,
            // MScriptDescription "GetModifierXPFountainCountdownTimeOverride"
            MODIFIER_PROPERTY_XP_FOUNTAIN_COUNTDOWN_TIME_OVERRIDE = 0x13d,
            // MScriptDescription "GetModifierNoFreeTPScrollOnDeath"
            MODIFIER_PROPERTY_NO_FREE_TP_SCROLL_ON_DEATH = 0x13e,
            // MScriptDescription "GetModifierHasBonusNeutralItemChoice"
            MODIFIER_PROPERTY_HAS_BONUS_NEUTRAL_ITEM_CHOICE = 0x13f,
            // MScriptDescription "HasBonusNeutralItemPassive"
            MODIFIER_PROPERTY_HAS_BONUS_NEUTRAL_ITEM_PASSIVE = 0x140,
            // MScriptDescription "GetModifierPreserveNeutralItemPassives"
            MODIFIER_PROPERTY_PRESERVE_NEUTRAL_ITEM_PASSIVES = 0x141,
            // MScriptDescription "GetModifierForceMaxHealth"
            MODIFIER_PROPERTY_FORCE_MAX_HEALTH = 0x142,
            // MScriptDescription "GetModifierForceMaxMana"
            MODIFIER_PROPERTY_FORCE_MAX_MANA = 0x143,
            // MScriptDescription "GetModifierAoEBonusConstant"
            MODIFIER_PROPERTY_AOE_BONUS_CONSTANT = 0x144,
            // MScriptDescription "GetModifierAoEBonusConstantStacking"
            MODIFIER_PROPERTY_AOE_BONUS_CONSTANT_STACKING = 0x145,
            // MScriptDescription "OnTakeDamagePostUnavoidableBlock"
            MODIFIER_EVENT_ON_TAKEDAMAGE_POST_UNAVOIDABLE_BLOCK = 0x146,
            // MScriptDescription "OnMuteDamageAbilities"
            MODIFIER_EVENT_ON_MUTE_DAMAGE_ABILITIES = 0x147,
            // MScriptDescription "GetSuppressCrit"
            MODIFIER_PROPERTY_SUPPRESS_CRIT = 0x148,
            // MScriptDescription "GetModifierAbilityPoints"
            MODIFIER_PROPERTY_ABILITY_POINTS = 0x149,
            // MScriptDescription "GetModifierBuybackPenaltyPercent"
            MODIFIER_PROPERTY_BUYBACK_PENALTY_PERCENT = 0x14a,
            // MScriptDescription "GetModifierItemSellbackCost"
            MODIFIER_PROPERTY_ITEM_SELLBACK_COST = 0x14b,
            // MScriptDescription "GetModifierDisassembleAnything"
            MODIFIER_PROPERTY_DISASSEMBLE_ANYTHING = 0x14c,
            // MScriptDescription "GetModifierFixedManaRegen"
            MODIFIER_PROPERTY_FIXED_MANA_REGEN = 0x14d,
            // MScriptDescription "GetModifierBonusUphillMissChance"
            MODIFIER_PROPERTY_BONUS_UPHILL_MISS_CHANCE = 0x14e,
            // MScriptDescription "GetModifierCreepDenyPercent"
            MODIFIER_PROPERTY_CREEP_DENY_PERCENT = 0x14f,
            // MScriptDescription "GetModifierAttackSpeedAbsoluteMax"
            MODIFIER_PROPERTY_ATTACKSPEED_ABSOLUTE_MAX = 0x150,
            // MScriptDescription "GetModifierFoWTeam"
            MODIFIER_PROPERTY_FOW_TEAM = 0x151,
            // MScriptDescription "OnHeroBeginDying"
            MODIFIER_EVENT_ON_HERO_BEGIN_DYING = 0x152,
            // MScriptDescription "GetModifierBonusLotusHeal"
            MODIFIER_PROPERTY_BONUS_LOTUS_HEAL = 0x153,
            // MScriptDescription "GetModifierBaseHpRegenPerStrBonusPercentage"
            MODIFIER_PROPERTY_BASE_HP_REGEN_PER_STR_BONUS_PERCENTAGE = 0x154,
            // MScriptDescription "GetModifierBaseArmorPerAgiBonusPercentage"
            MODIFIER_PROPERTY_BASE_ARMOR_PER_AGI_BONUS_PERCENTAGE = 0x155,
            // MScriptDescription "GetModifierBaseAttackSpeedPerAgiBonusPercentage"
            MODIFIER_PROPERTY_BASE_ATTACKSPEED_PER_AGI_BONUS_PERCENTAGE = 0x156,
            // MScriptDescription "GetModifierBaseManaRegenPerIntBonusPercentage"
            MODIFIER_PROPERTY_BASE_MP_REGEN_PER_INT_BONUS_PERCENTAGE = 0x157,
            // MScriptDescription "GetModifierBaseMagicResistPerIntBonusPercentage"
            MODIFIER_PROPERTY_BASE_MRES_PER_INT_BONUS_PERCENTAGE = 0x158,
            // MScriptDescription "OnDayStarted"
            MODIFIER_EVENT_ON_DAY_STARTED = 0x159,
            // MScriptDescription "OnNightStarted"
            MODIFIER_EVENT_ON_NIGHT_STARTED = 0x15a,
            // MScriptDescription "GetModifierCreateBonusIllusionChance"
            MODIFIER_PROPERTY_CREATE_BONUS_ILLUSION_CHANCE = 0x15b,
            // MScriptDescription "GetModifierCreateBonusIllusionCount"
            MODIFIER_PROPERTY_CREATE_BONUS_ILLUSION_COUNT = 0x15c,
            // MScriptDescription "GetModofierPropertyPseudoRandomBonus"
            MODIFIER_PROPERTY_PSEUDORANDOM_BONUS = 0x15d,
            // MScriptDescription "GetModifierAttackHeightBonus"
            MODIFIER_PROPERTY_ATTACK_HEIGHT_BONUS = 0x15e,
            // MScriptDescription "GetSkipAttackRegulator"
            MODIFIER_PROPERTY_SKIP_ATTACK_REGULATOR = 0x15f,
            // MScriptDescription "GetModifierMiss_Percentage_Target"
            MODIFIER_PROPERTY_MISS_PERCENTAGE_TARGET = 0x160,
            // MScriptDescription "GetModifierAdditionalNutralItemDrops"
            MODIFIER_PROPERTY_ADDITIONAL_NEUTRAL_ITEM_DROPS = 0x161,
            // MScriptDescription "GetModifierKillStreakBonusGoldPercentage"
            MODIFIER_PROPERTY_KILL_STREAK_BONUS_GOLD_PERCENTAGE = 0x162,
            // MScriptDescription "GetModifierHPRegenMultiplierPreAmplification"
            MODIFIER_PROPERTY_HP_REGEN_MULTIPLIER_PRE_AMPLIFICATION = 0x163,
            // MScriptDescription "GetModifierHeroFacetOverride"
            MODIFIER_PROPERTY_HEROFACET_OVERRIDE = 0x164,
            // MScriptDescription "OnTreeCutDown"
            MODIFIER_EVENT_ON_TREE_CUT_DOWN = 0x165,
            // MScriptDescription "OnCleaveAttackLanded"
            MODIFIER_EVENT_ON_CLEAVE_ATTACK_LANDED = 0x166,
            // MScriptDescription "MinAttributeLevel"
            MODIFIER_PROPERTY_MIN_ATTRIBUTE_LEVEL = 0x167,
            // MScriptDescription "GetTierTokenReroll"
            MODIFIER_PROPERTY_TIER_TOKEN_REROLL = 0x168,
            // MScriptDescription "GetVisionDegreeRestriction"
            MODIFIER_PROPERTY_VISION_DEGREES_RESTRICTION = 0x169,
            // MScriptDescription "GetModifierTotal_ConstantBlockStacking"
            MODIFIER_PROPERTY_TOTAL_CONSTANT_BLOCK_STACKING = 0x16a,
            // MScriptDescription "GetModifierInventorySlotRestricted"
            MODIFIER_PROPERTY_INVENTORY_SLOT_RESTRICTED = 0x16b,
            // MScriptDescription "OnTierTokenRerolled"
            MODIFIER_EVENT_ON_TIER_TOKEN_REROLLED = 0x16c,
            // MScriptDescription "GetRedirectSpell"
            MODIFIER_PROPERTY_REDIRECT_SPELL = 0x16d,
            // MScriptDescription "GetBaseAttackPostBonus"
            MODIFIER_PROPERTY_BASEATTACK_POSTBONUS = 0x16e,
            // MScriptDescription "OnFoWTeamChanged"
            MODIFIER_EVENT_ON_FOW_TEAM_CHANGED = 0x16f,
            // MScriptDescription "GetSuppressAttackProcs"
            MODIFIER_PROPERTY_SUPPRESS_ATTACK_PROCS = 0x170,
            // MScriptDescription "OnAbilityToggled"
            MODIFIER_EVENT_ON_ABILITY_TOGGLED = 0x171,
            // MScriptDescription "GetModifierAvoidAttackProcs"
            MODIFIER_PROPERTY_AVOID_ATTACK_PROCS = 0x172,
            // MScriptDescription "OnRuneSpawn"
            MODIFIER_EVENT_ON_RUNE_SPAWN = 0x173,
            // MScriptDescription "GetModifierProperty_PhysicalLifesteal"
            MODIFIER_PROPERTY_PHYSICAL_LIFESTEAL = 0x174,
            // MScriptDescription "GetModifierProperty_MagicalLifesteal"
            MODIFIER_PROPERTY_MAGICAL_LIFESTEAL = 0x175,
            // MScriptDescription "OnPureDamageCalculated"
            MODIFIER_EVENT_ON_PURE_DAMAGE_CALCULATED = 0x176,
            // MScriptDescription "GetModifierNeutralTrinketOptions"
            MODIFIER_EVENT_NEUTRAL_TRINKET_OPTIONS = 0x177,
            // MScriptDescription "GetModifierNeutralEnhancementOptions"
            MODIFIER_EVENT_NEUTRAL_ENHANCEMENT_OPTIONS = 0x178,
            // MScriptDescription "GetModifierMoveSpeedMax_BonusConstant"
            MODIFIER_PROPERTY_MOVESPEED_MAX_BONUS_CONSTANT = 0x179,
            // MScriptDescription "GetModifierMoveSpeedPostMultiplierBonus_Constant"
            MODIFIER_PROPERTY_MOVESPEED_POST_MULTIPLIER_BONUS_CONSTANT = 0x17a,
            // MScriptDescription "GetModifierPropertyForbidIllusions"
            MODIFIER_PROPERTY_FORBID_ILLUSIONS = 0x17b,
            // MScriptDescription "GetModifierPropertyManacostOverride"
            MODIFIER_PROPERTY_MANACOST_OVERRIDE = 0x17c,
            // MScriptDescription "GetModifierPropertyRestorationAmplification"
            MODIFIER_PROPERTY_RESTORATION_AMPLIFICATION = 0x17d,
            // MScriptDescription "GetModifierPropertyRestorationAmplificationUnique"
            MODIFIER_PROPERTY_RESTORATION_AMPLIFICATION_UNIQUE = 0x17e,
            // MScriptDescription "GetModifierPropertyHealingAmplificationUnique"
            MODIFIER_PROPERTY_HEAL_AMPLIFY_PERCENTAGE_SOURCE_UNIQUE = 0x17f,
            // MScriptDescription "GetModifierPropertyRedirectHealthGain"
            MODIFIER_PROPERTY_REDIRECT_HEALTH_GAIN = 0x180,
            // MScriptDescription "GetSuppressIncomingCrit"
            MODIFIER_PROPERTY_SUPPRESS_INCOMING_CRIT = 0x181,
            // MScriptDescription "GetModifierPropertyUpgradeNeutralArtifacts"
            MODIFIER_PROPERTY_UPGRADE_NEUTRAL_ARTIFACTS = 0x182,
            // MScriptDescription "GetModifierPropertySuppressInvalidMoveAttackOrders"
            MODIFIER_PROPERTY_SUPPRESS_INVALID_MOVE_ATTACK_ORDERS = 0x183,
            // MScriptDescription "GetModifierPropertyConsumableUseSpeed"
            MODIFIER_PROPERTY_CONSUMABLE_USE_SPEED = 0x184,
            // MScriptDescription "GetRequiredLevel"
            MODIFIER_PROPERTY_REQUIRED_LEVEL = 0x185,
            // MScriptDescription "OnModifierRefreshed"
            MODIFIER_EVENT_ON_MODIFIER_REFRESHED = 0x186,
            // MScriptDescription "OnAbilitySwapped"
            MODIFIER_EVENT_ON_ABILITY_SWAPPED = 0x187,
            // MScriptDescription "GetModifierOverrideCreepBounty"
            MODIFIER_PROPERTY_OVERRIDE_CREEP_BOUNTY = 0x188,
            // MScriptDescription "GetModifierOverrideBaseDamage"
            MODIFIER_PROPERTY_OVERRIDE_BASE_DAMAGE = 0x189,
            // MScriptDescription "GetModifierOverrideUntargetableFrom"
            MODIFIER_PROPERTY_UNTARGETABLE_FROM = 0x18a,
            // MScriptDescription "GetModifierOverrideUntargetableTo"
            MODIFIER_PROPERTY_UNTARGETABLE_TO = 0x18b,
            // MScriptDescription "GetModifierSuperIllusionWithItems"
            MODIFIER_PROPERTY_SUPER_ILLUSION_WITH_ITEMS = 0x18c,
            // MScriptDescription "OnPurged"
            MODIFIER_EVENT_ON_PURGE = 0x18d,
            // MScriptDescription "OnIllusionCreated"
            MODIFIER_EVENT_ON_ILLUSION_CREATED = 0x18e,
            // MScriptDescription "GetModifierHeroLevelScale"
            MODIFIER_PROPERTY_HEROLEVELSCALE = 0x18f,
            // MScriptDescription "GetModifierReplaceAttack"
            MODIFIER_PROPERTY_REPLACE_ATTACK = 0x190,
            // MScriptDescription "GetModifierPropertyCustom1"
            MODIFIER_PROPERTY_CUSTOM1 = 0x191,
            // MScriptDescription "GetModifierPropertyCustom2"
            MODIFIER_PROPERTY_CUSTOM2 = 0x192,
            // MScriptDescription "GetModifierPropertyCustom3"
            MODIFIER_PROPERTY_CUSTOM3 = 0x193,
            // MScriptDescription "OnCustom1"
            MODIFIER_EVENT_ON_CUSTOM1 = 0x194,
            // MScriptDescription "OnCustom2"
            MODIFIER_EVENT_ON_CUSTOM2 = 0x195,
            // MScriptDescription "OnCustom3"
            MODIFIER_EVENT_ON_CUSTOM3 = 0x196,
            MODIFIER_FUNCTION_LAST = 0x197,
            MODIFIER_FUNCTION_INVALID = 0xffff,
        };
    };
};
